server:
  port: 9528

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9527/eureka

spring:
  application:
    name: XFORCE
  datasource:
    url: jdbc:mysql://localhost:3306/zwm
    username: root
    password: root